// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDrJnT9bTEseYapegxvB_BBB4A_eiFrs',
    appId: '1:517672995365:web:4b30bf86efdb714d5b8dcc',
    messagingSenderId: '517672995365',
    projectId: 'mboatoscope',
    authDomain: 'mboatoscope.firebaseapp.com',
    databaseURL: 'https://mboatoscope-default-rtdb.firebaseio.com',
    storageBucket: 'mboatoscope.appspot.com',
    measurementId: 'G-EL67DWKS5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhcm9gBFNbAWXEvjxEtrFkoazhKgp0HoY',
    appId: '1:517672995365:android:f54c89f59c80ea2d5b8dcc',
    messagingSenderId: '517672995365',
    projectId: 'mboatoscope',
    databaseURL: 'https://mboatoscope-default-rtdb.firebaseio.com',
    storageBucket: 'mboatoscope.appspot.com',
  );
}
